### PR TITLE
Handlebars updates 

### PR DESCRIPTION
**Pull request by ErisDS**
- Renamed `@blog` -> `@site`
- Updated package.json with ghost-api v2 info
- Made all the helpers into links

### CODE REVIEW

**Review by kymellis — APPROVED** [review]

**Review by JohnONolan — APPROVED** [review]

**Comment by JohnONolan** [comment]
Merge conflict @ErisDS

**Comment by JohnONolan** [comment]
ping @ErisDS

**Review by kymellis — APPROVED** [review]

**Comment by kymellis** [comment]
Woops ignore that approval.

**Comment by kymellis** [comment]
@JohnONolan I have made all of the changes in this PR now as discussed.

The updates to: `src/data/sidebars/handlebars.yaml` & `static/_redirects` pushed straight to master and all of the updated files in `content/api/v2` were already updated. I submitted a PR to fix a typo in docs-api.

**Pull request closed without merging**
