### PR TITLE
Github -> GitHub

### PR DESCRIPTION
**Pull request by JasonEtco**
Hi! This PR updates `Github` to be `GitHub` - the uppercase H is the correct way to spell it 😊

I did a case-sensitive "Find-and-replace-all" to find these. Let me know if anythings missing!

### CODE REVIEW

**Comment by JohnONolan** [comment]
Thanks! It's also `Ghost` rather than `TryGhost` - let me know if there's been any change in the last few years and if it's now possible to re-assign the default username of deleted accounts to something else :)

**Comment by JasonEtco** [comment]
@JohnONolan unfortunately no, we still use `@ghost` as the account for deleted accounts 😞 that's actually really disappointing given this project. I'm not at all the right person to talk to, but [contacting support](https://git.io/c) is probably your best option (but I wouldn't bet on it 😭)

**Comment by JohnONolan** [comment]
Yeah, been down that road already. Thanks though!

**Comment by JasonEtco** [comment]
Sure! Sorry I couldn't be of more help 👻

**Pull request merged**
